// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: grpc/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MutexNodeVTwo_SendToken_FullMethodName = "/MutexNodeVTwo/SendToken"
)

// MutexNodeVTwoClient is the client API for MutexNodeVTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MutexNodeVTwoClient interface {
	SendToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type mutexNodeVTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewMutexNodeVTwoClient(cc grpc.ClientConnInterface) MutexNodeVTwoClient {
	return &mutexNodeVTwoClient{cc}
}

func (c *mutexNodeVTwoClient) SendToken(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MutexNodeVTwo_SendToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutexNodeVTwoServer is the server API for MutexNodeVTwo service.
// All implementations must embed UnimplementedMutexNodeVTwoServer
// for forward compatibility.
type MutexNodeVTwoServer interface {
	SendToken(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedMutexNodeVTwoServer()
}

// UnimplementedMutexNodeVTwoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMutexNodeVTwoServer struct{}

func (UnimplementedMutexNodeVTwoServer) SendToken(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToken not implemented")
}
func (UnimplementedMutexNodeVTwoServer) mustEmbedUnimplementedMutexNodeVTwoServer() {}
func (UnimplementedMutexNodeVTwoServer) testEmbeddedByValue()                       {}

// UnsafeMutexNodeVTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutexNodeVTwoServer will
// result in compilation errors.
type UnsafeMutexNodeVTwoServer interface {
	mustEmbedUnimplementedMutexNodeVTwoServer()
}

func RegisterMutexNodeVTwoServer(s grpc.ServiceRegistrar, srv MutexNodeVTwoServer) {
	// If the following call pancis, it indicates UnimplementedMutexNodeVTwoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MutexNodeVTwo_ServiceDesc, srv)
}

func _MutexNodeVTwo_SendToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutexNodeVTwoServer).SendToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MutexNodeVTwo_SendToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutexNodeVTwoServer).SendToken(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// MutexNodeVTwo_ServiceDesc is the grpc.ServiceDesc for MutexNodeVTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MutexNodeVTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MutexNodeVTwo",
	HandlerType: (*MutexNodeVTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToken",
			Handler:    _MutexNodeVTwo_SendToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto.proto",
}
